#! /bin/sh

### BEGIN INIT INFO
# Provides:		lxc-web-panel
# Required-Start:	$remote_fs $syslog $network
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		
# Short-Description:	Lxc Web Panel
### END INIT INFO

set -e

NAME=lxc-web-panel
DESC="Lxc Web Panel"
LWP_EXEC=/usr/bin/python
LWP_WORKDIR=/var/www/LXC-Web-Panel
LWP_DAEMON=lwp.py
LWP_PID=/var/run/$NAME.pid
LWP_USER=root
LWP_GROUP=www-data

test -x $LWP_EXEC || exit 1

umask 022

if test -f /etc/default/$NAME; then
    . /etc/default/$NAME
fi

. /lib/lsb/init-functions

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
	log_daemon_msg "Starting $DESC server" "$NAME" || true
	if start-stop-daemon --background --user $LWP_USER --group $LWP_GROUP --chdir $LWP_WORKDIR --start --quiet --make-pidfile --pidfile $LWP_PID --exec $LWP_EXEC -- $LWP_DAEMON; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;
  stop)
	log_daemon_msg "Stopping $DESC server" "$NAME" || true
	if start-stop-daemon --stop --quiet --oknodo --pidfile $LWP_PID; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  restart)
	$0 stop
	sleep 1
	$0 start
	;;

  status)
	status_of_proc -p $LWP_PID $LWP_EXEC $NAME && exit 0 || exit $?
	;;

  *)
	log_action_msg "Usage: /etc/init.d/$NAME {start|stop|restart|status}" || true
	exit 1
esac

exit 0
